parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Api\:
        resource: '../src/Api'
        tags: ['api.service_arguments']

    user_service:
        class: App\Service\UserService

    budget_request_service:
        class: App\Service\BudgetRequestService

    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        public: false
        tags: [serializer.normalizer]